### ISSUE TITLE
Oblivion theme

### ISSUE THREAD

**Issue by nerun** [kemelzaidan/ghostwriter-themes#1]
Please, add my ghostwriter theme based upon Oblivion theme for Gedit / Pluma / Xed. Copy to yours ~/.config/ghostwriter/themes.

```json
{
    "dark": {
        "accent": "#ac7e9a",
        "background": "#2e3436",
        "block": "#bdc3c7",
        "cursor": "#3daee9",
        "emphasis": "#8ae234",
        "error": "#da4453",
        "foreground": "#d3d3a9",
        "heading": "#ca6b0d",
        "link": "#3daee9",
        "markup": "#ebd207",
        "selection": "#93cee9"
    },
    "light": {
        "accent": "#dc143c",
        "background": "#faf0e6",
        "block": "#808080",
        "cursor": "#3daee9",
        "emphasis": "#008000",
        "error": "#bc3b48",
        "foreground": "#414134",
        "heading": "#5e3006",
        "link": "#0000ff",
        "markup": "#c29307",
        "selection": "#93cee9"
    }
}
```

This theme was intended to be used in dark mode, the light mode was created only because it was necessary to have a light theme in order to create a theme for Ghostwriter.

| DARK | LIGHT |
|:------:|:------:|
| ![dark](https://user-images.githubusercontent.com/3987342/292010640-9be46a24-0864-46ec-a8b2-d612779bde0c.png) | ![light](https://user-images.githubusercontent.com/3987342/292010719-17b795c6-b224-404e-b4f7-8a6b2cf8483d.png) |

## Installation
Copy `Oblivion.json` to `~/.config/ghostwriter/themes`.

**Comment by kemelzaidan** [comment]
Done. Thanks for the theme! :+1:
